version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.2
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.3.3
    - 6.3.4
  - dependency-name: logrocket
    versions:
    - 1.1.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 4.2.0
    - 4.4.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 3.2.0
    - 3.4.0
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.4.0
  - dependency-name: gatsby-plugin-gatsby-cloud
    versions:
    - 2.2.0
    - 2.3.0
    - 2.4.0
  - dependency-name: gatsby
    versions:
    - 3.3.1
  - dependency-name: gatsby-source-filesystem
    versions:
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-image
    versions:
    - 1.2.0
    - 1.2.1
    - 1.3.0
    - 1.3.1
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 4.2.0
    - 4.3.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.23.0
  - dependency-name: classnames
    versions:
    - 2.3.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 3.2.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: dompurify
    versions:
    - 2.2.6
    - 2.2.7
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: react-autosuggest
    versions:
    - 10.1.0
  - dependency-name: react
    versions:
    - 16.14.0
