name: integrations tests
on: [push]
jobs:

  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0 # match .tool-versions file
      - name: Cypress integration tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run build:serve
          wait-on: 'http://localhost:9000'
          wait-on-timeout: 500 # seconds = 6 mins
          config: 'baseUrl=http://localhost:9000'

  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0 # match .tool-versions file
      - name: Cypress data validation
        uses: cypress-io/github-action@v6
        with:
          env: VALIDATE_ALL=true
          spec: cypress/e2e/zz-validate-data.cy.js
          start: npm run build:serve:9001
          wait-on: 'http://localhost:9001'
          wait-on-timeout: 500 # seconds = 6 mins
          config: 'baseUrl=http://localhost:9001'
