name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node 16.13.2
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run build:serve
          wait-on: 'http://localhost:9000'
          wait-on-timeout: 300 # seconds = 5 mins
          config: 'baseUrl=http://localhost:9000,retries=1'

